export const isdCodes = [
    { code: "1", country: "US/Canada" },
    { code: "44", country: "United Kingdom" },
    { code: "91", country: "India" },
    { code: "86", country: "China" },
    { code: "81", country: "Japan" },
    { code: "49", country: "Germany" },
    { code: "33", country: "France" },
    { code: "39", country: "Italy" },
    { code: "61", country: "Australia" },
    { code: "7", country: "Russia" },
    { code: "82", country: "South Korea" },
    { code: "34", country: "Spain" },
    { code: "52", country: "Mexico" },
    { code: "55", country: "Brazil" },
    { code: "65", country: "Singapore" },
    { code: "971", country: "UAE" },
    { code: "966", country: "Saudi Arabia" },
    { code: "60", country: "Malaysia" },
    { code: "62", country: "Indonesia" },
    { code: "63", country: "Philippines" },
    { code: "64", country: "New Zealand" },
    { code: "66", country: "Thailand" },
    { code: "84", country: "Vietnam" },
    { code: "92", country: "Pakistan" },
    { code: "880", country: "Bangladesh" },
    { code: "94", country: "Sri Lanka" },
    { code: "977", country: "Nepal" },
];
