export const wmsRoles = [
  { id: 3, name: "PICKER", description: "Unit Picker Role" },
  { id: 4, name: "PACKER", description: "Unit Packer Role" },
  { id: 5, name: "INBOUND QC OPERATOR", description: "Unit Inbound QC Operator Role" },
  { id: 6, name: "INBOUND PUTAWAY OPERATOR", description: "Unit Inbound Putaway Operator Role" },
  { id: 7, name: "SECURITY GUARD", description: "Unit Security Guard Role" },
  { id: 8, name: "RECEIVER", description: "Unit receiver Role" },
  { id: 9, name: "WAREHOUSE OPERATOR", description: "Unit Warehouse Operator Role" },
  { id: 10, name: "OUTBOUND QC OPERATOR", description: "Unit Outbound QC Operator Role" },
  { id: 11, name: "SUPER ADMIN", description: "super admin role" },
  { id: 2, name: "ADMIN", description: "basic admin" },
  { id: 12, name: "SCWB", description: "Works on SCWB Panels" },
  { id: 13, name: "VENDOR", description: "vendor" },
  { id: 14, name: "FINANCE ADMIN", description: "finance-admin" },
  { id: 15, name: "BUYER", description: "buyer" },
  { id: 16, name: "MANAGER", description: "manager" },
  { id: 17, name: "COE", description: "coe" },
  { id: 18, name: "PROCURO-ADMIN", description: "procuro-admin" },
  { id: 19, name: "PROCUREMENT OFFICER", description: "procurement officer" },
  { id: 20, name: "L1 APPROVER", description: "L1 Approver" },
  { id: 21, name: "L2 APPROVER", description: "L2 Approver" },
  { id: 22, name: "L3 APPROVER", description: "L3 Approver" },
  { id: 23, name: "PICKER+ADMIN+L2_APPROVAL", description: "picker+admin+l2_approval" },
  { id: 24, name: "MASTER ADMIN", description: "Having all access of procuro + admin" },
  { id: 25, name: "ADMIN + L2 APPROVER", description: "Admin + L2 Approver" },
  { id: 26, name: "ADMIN + L1 APPROVER", description: "ADMIN + L1 APPROVER" },
  { id: 27, name: "DEMO", description: "For demo purpose" },
  { id: 28, name: "ADMIN0", description: "Admin without PO approval" },
];
